"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MMOnlineEvents = void 0;
var MMOnlineEvents;
(function (MMOnlineEvents) {
    MMOnlineEvents["PLAYER_PUPPET_PRESPAWN"] = "MMOnline:onPlayerPuppetPreSpawned";
    MMOnlineEvents["PLAYER_PUPPET_SPAWNED"] = "MMOnline:onPlayerPuppetSpawned";
    MMOnlineEvents["PLAYER_PUPPET_DESPAWNED"] = "MMOnline:onPlayerPuppetDespawned";
    MMOnlineEvents["PLAYER_PUPPET_QUERY"] = "MMOnline:PlayerPuppetQuery";
    MMOnlineEvents["SERVER_PLAYER_CHANGED_SCENES"] = "MMOnline:onServerPlayerChangedScenes";
    MMOnlineEvents["CLIENT_REMOTE_PLAYER_CHANGED_SCENES"] = "MMOnline:onRemotePlayerChangedScenes";
    MMOnlineEvents["GHOST_MODE"] = "MMOnline:EnableGhostMode";
    MMOnlineEvents["GAINED_HEART_CONTAINER"] = "MMOnline:GainedHeartContainer";
    MMOnlineEvents["GAINED_PIECE_OF_HEART"] = "MMOnline:GainedPieceOfHeart";
    MMOnlineEvents["MAGIC_METER_INCREASED"] = "MMOnline:GainedMagicMeter";
    MMOnlineEvents["CUSTOM_MODEL_APPLIED_ADULT"] = "MMOnline:ApplyCustomModelAdult";
    MMOnlineEvents["CUSTOM_MODEL_APPLIED_CHILD"] = "MMOnline:ApplyCustomModelChild";
    MMOnlineEvents["CUSTOM_MODEL_APPLIED_ANIMATIONS"] = "MMOnline:ApplyCustomAnims";
    MMOnlineEvents["CUSTOM_MODEL_APPLIED_ICON_ADULT"] = "MMOnline:ApplyCustomIconAdult";
    MMOnlineEvents["CUSTOM_MODEL_APPLIED_ICON_CHILD"] = "MMOnline:ApplyCustomIconChild";
    MMOnlineEvents["ON_INVENTORY_UPDATE"] = "MMOnline:OnInventoryUpdate";
    MMOnlineEvents["ON_EXTERNAL_ACTOR_SYNC_LOAD"] = "MMOnline:OnExternalActorSyncLoad";
    MMOnlineEvents["ON_REGISTER_EMOTE"] = "MMOnline:OnRegisterEmote";
    MMOnlineEvents["ON_LOAD_SOUND_PACK"] = "MMOnline:OnLoadSoundPack";
    MMOnlineEvents["ON_REMOTE_SOUND_PACK"] = "MMOnline:OnRemoteSoundPack";
    MMOnlineEvents["ON_REMOTE_PLAY_SOUND"] = "MMOnline:OnRemotePlaySound";
    MMOnlineEvents["CUSTOM_MODEL_LOAD_BUFFER_ADULT"] = "MMOnline:ApplyCustomModelAdultBuffer";
    MMOnlineEvents["CUSTOM_MODEL_LOAD_BUFFER_CHILD"] = "MMOnline:ApplyCustomModelChildBuffer";
    MMOnlineEvents["ALLOCATE_MODEL_BLOCK"] = "MMOnline:AllocateModelBlock";
    MMOnlineEvents["FORCE_LOAD_MODEL_BLOCK"] = "MMOnline:ForceLoadModelBlock";
    MMOnlineEvents["CHANGE_CUSTOM_MODEL_ADULT_GAMEPLAY"] = "MMOnline:ChangeCustomModelAdultGamePlay";
    MMOnlineEvents["CHANGE_CUSTOM_MODEL_CHILD_GAMEPLAY"] = "MMOnline:ChangeCustomModelChildGamePlay";
    MMOnlineEvents["FORCE_PUPPET_RESPAWN_IMMEDIATE"] = "MMOnline:ForcePuppetRespawnImmediate";
    MMOnlineEvents["POST_LOADED_MODELS_LIST"] = "MMOnline:PostLoadedModelsList";
    MMOnlineEvents["LOAD_EQUIPMENT_BUFFER"] = "MMOnline:LoadEquipmentBuffer";
    MMOnlineEvents["LOAD_EQUIPMENT_PAK"] = "MMOnline:LoadEquipmentPak";
    MMOnlineEvents["REFRESH_EQUIPMENT"] = "MMOnline:RefreshEquipment";
    MMOnlineEvents["CLEAR_EQUIPMENT"] = "MMOnline:ClearEquipment";
    MMOnlineEvents["SWORD_NEEDS_UPDATE"] = "MmOnline:UpdateSwordB";
})(MMOnlineEvents = exports.MMOnlineEvents || (exports.MMOnlineEvents = {}));
//# sourceMappingURL=MMAPI.js.map